sudo: required
dist: trusty
before_install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle binstub rake
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby
gemfile:
  - gemfiles/omniauth-oauth2-1.4.gemfile
  - gemfiles/omniauth-oauth2-1.6.gemfile
