name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: '2.7', oauth2: '1.6' }
          - { ruby: '2.7', oauth2: '1.7' }
          - { ruby: '2.7', oauth2: '1.8' }
          - { ruby: '3.0', oauth2: '1.6' }
          - { ruby: '3.0', oauth2: '1.7' }
          - { ruby: '3.0', oauth2: '1.8' }
          - { ruby: '3.1', oauth2: '1.6' }
          - { ruby: '3.1', oauth2: '1.7' }
          - { ruby: '3.1', oauth2: '1.8' }
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/omniauth_oauth2_${{ matrix.oauth2 }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake spec
